# Generated by Django 4.2.7 on 2025-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Hero section banner image', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Site favicon (.ico or .png)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main site logo', null=True, upload_to='branding/'),
        ),
    ]
