# Generated by Django 4.2.7 on 2025-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='library_opens_new_tab',
            field=models.BooleanField(default=True, help_text='Open library link in new tab'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='library_url',
            field=models.URLField(blank=True, help_text='External library/resources URL (optional)'),
        ),
    ]
