# Generated by Django 4.2.7 on 2025-07-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_library_opens_new_tab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_user_registration',
            field=models.BooleanField(default=True, help_text='Allow new user registration'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_footer_scripts',
            field=models.TextField(blank=True, help_text='Custom scripts to include before </body>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_header_scripts',
            field=models.TextField(blank=True, help_text='Custom scripts to include in <head>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Put site in maintenance mode'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_email_verification',
            field=models.BooleanField(default=True, help_text='Require email verification for new users'),
        ),
    ]
