# Generated by Django 4.2.7 on 2025-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_allow_user_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='accent_color',
            field=models.CharField(default='#F59E0B', help_text='Accent brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS styles'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#10B981', help_text='Secondary brand color (hex)', max_length=7),
        ),
    ]
