# Generated by Django 4.2.7 on 2025-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text="Default 'from' email address", max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_backend',
            field=models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console (Development)'), ('django.core.mail.backends.dummy.EmailBackend', 'Dummy (No Email)')], default='django.core.mail.backends.console.EmailBackend', help_text='Email backend to use', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password/app password', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP username/email', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL encryption'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
    ]
