# Generated by Django 4.2.7 on 2025-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_page_image',
            field=models.ImageField(blank=True, help_text='About page hero image', null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='consultancy_default_image',
            field=models.ImageField(blank=True, help_text='Default image for Consultancy services', null=True, upload_to='defaults/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_page_image',
            field=models.ImageField(blank=True, help_text='Contact page hero image', null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='digital_default_image',
            field=models.ImageField(blank=True, help_text='Default image for Digital Skills services', null=True, upload_to='defaults/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='general_default_image',
            field=models.ImageField(blank=True, help_text='General default image for services', null=True, upload_to='defaults/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main hero section image', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='resources_page_image',
            field=models.ImageField(blank=True, help_text='Resources page hero image', null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='scholarship_default_image',
            field=models.ImageField(blank=True, help_text='Default image for Scholarship services', null=True, upload_to='defaults/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='services_page_image',
            field=models.ImageField(blank=True, help_text='Services page hero image', null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='university_default_image',
            field=models.ImageField(blank=True, help_text='Default image for University services', null=True, upload_to='defaults/'),
        ),
    ]
