# Generated by Django 4.2.7 on 2025-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_about_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_approach_image',
            field=models.ImageField(blank=True, help_text='Our Approach section image', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_mission_image',
            field=models.ImageField(blank=True, help_text='Our Mission section image', null=True, upload_to='about/'),
        ),
    ]
