# Generated by Django 4.2.7 on 2025-07-23 20:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfiguration_about_approach_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_host_password',
            field=core.models.EncryptedCharField(blank=True, help_text='SMTP password/app password (encrypted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Edunox GH', max_length=100),
        ),
    ]
