# Generated by Django 4.2.7 on 2025-07-25 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_booking_is_consultancy_booking_booking_quoted_price_and_more'),
        ('core', '0009_encrypt_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='jobs_opens_new_tab',
            field=models.BooleanField(default=True, help_text='Open jobs link in new tab'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='jobs_url',
            field=models.URLField(blank=True, help_text='External jobs/careers URL (optional)'),
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_type', models.CharField(choices=[('services', 'Services Dropdown'), ('main', 'Main Navigation')], default='services', max_length=20)),
                ('name', models.CharField(help_text='Display name for the menu item', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fas fa-university)', max_length=50)),
                ('link_type', models.CharField(choices=[('internal', 'Internal Page'), ('external', 'External URL'), ('service', 'Service Page')], default='internal', max_length=20)),
                ('internal_url_name', models.CharField(blank=True, help_text='Django URL name (e.g., services:list)', max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='External URL (for external links)')),
                ('opens_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('group_name', models.CharField(blank=True, help_text="Group name for services dropdown (e.g., 'University Applications')", max_length=100)),
                ('service', models.ForeignKey(blank=True, help_text='Link to specific service', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['menu_type', 'order', 'name'],
            },
        ),
    ]
