# Generated by Django 4.2.7 on 2025-07-22 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_consultancy_booking',
            field=models.BooleanField(default=False, help_text='Covered by consultancy package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-quoted price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='admin_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-set price in GHS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_one_time_consultancy',
            field=models.BooleanField(default=False, help_text='Part of one-time consultancy package'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('ADMIN_SET', 'Admin Set Price'), ('ONE_TIME_CONSULTANCY', 'One-Time Consultancy'), ('FREE', 'Free Service')], default='FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in GHS', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OneTimeConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Complete Educational Consultancy Package', max_length=200)),
                ('description', models.TextField(default='Get access to all our services with one payment')),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price in GHS', max_digits=10)),
                ('duration_months', models.PositiveIntegerField(default=12, help_text='Package validity in months')),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.TextField(help_text='List of package features, one per line')),
                ('included_services', models.ManyToManyField(blank=True, help_text='Services included in this package', to='services.service')),
            ],
            options={
                'verbose_name': 'One-Time Consultancy Package',
                'verbose_name_plural': 'One-Time Consultancy Packages',
            },
        ),
        migrations.CreateModel(
            name='ConsultancyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.onetimeconsultancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultancy Purchase',
                'verbose_name_plural': 'Consultancy Purchases',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='consultancy_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.consultancypurchase'),
        ),
    ]
